fn main() {
    // Tauri 2 的应用自定义命令默认**不放行**:得在这里登记,tauri-build 会生成
    // permissions/autogenerated/ 下的 allow-<命令> 权限,再由 capabilities/default.json 引用。
    // 没登记的命令前端 invoke 时报「not allowed. Plugin not found」—— 三个 proc_lock 命令
    // 以前就是这么静默失败的(前端那边 catch 掉了,所以没人发现)。
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(&[
            "acquire_proc_lock",
            "release_proc_lock",
            "is_proc_locked",
            "agent_webview_show",
            "agent_webview_hide",
            "agent_webview_mute",
            "agent_webview_info",
            "menu_bar_color",
        ])),
    )
    .expect("tauri-build 失败");
}
