import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { randomBytes, createHash } from 'node:crypto';
import { createHostingService } from '../hosting/service.mjs';
import { startHostingHost } from '../hosting/host.mjs';
import { discoverRoom, relayFetch, authorizeRelayAsset } from '../hosting/client.mjs';
import { startHostedCombo } from '../hosted/combo.mjs';
import { createSharedProject, buildAuthProtocols } from '../auth/client.mjs';
import { createAssetClient } from '../asset-store/client.mjs';
import { wsClient, waitFor } from './fake-ws-kit.mjs';
const temp = () => fs.mkdtempSync(path.join(os.tmpdir(), 'pc-reopen-hosting-'));
const key = () => randomBytes(32).toString('base64url');
let seq = 0;
async function ask(c, m) { const reqId = `rh-${++seq}`; c.send({ ...m, reqId }); try { return await c.next(x => x.reqId === reqId); } catch { throw new Error(`等待 ${m.type} 响应超时（秘密已省略）`); } }
for (const mode of ['free', 'restricted']) test(`真实中继 ${mode}：登记认证、独占租约、双向编辑、带票据素材读写、删除墓碑`, { timeout: 30000 }, async t => {
  const dir = temp(), cloud = createHostingService({ dir }); const addr = await cloud.listen(); const service = `http://127.0.0.1:${addr.port}`;
  t.after(() => cloud.close());
  const c = await startHostedCombo({ dataDir: temp(), docPort: 0, assetPort: 0, host: '127.0.0.1', trustLoopback: false, clusterToken: key(), log: () => {} }); t.after(() => c.close());
  const localBase = `http://127.0.0.1:${c.docPort}`;
  const creatorPassword = key(), password = key(), memberPassword = mode === 'free' ? password : key();
  const p = await createSharedProject({ base: localBase, name: `isolated-reopen-${mode}`, mode, creator: { username: 'host', password: creatorPassword }, password,
    list: [{ username: 'member', password: memberPassword }], kdf: { alg: 'pbkdf2-sha256', iter: 100000 } });
  const docUrl = localBase.replace('http:', 'ws:');
  const host = wsClient(docUrl, await buildAuthProtocols({ base: localBase, projectId: p.projectId, username: 'host', as: 'creator', password: creatorPassword, deviceId: 'host-original-device-0001', deviceName: 'isolated-host' })); await host.opened; t.after(() => host.close());
  await ask(host, { type: 'project.open', projectId: p.projectId });
  assert.equal((await ask(host, { type: 'project.op', projectId: p.projectId, opId: key(), ops: [{ op: 'set', path: '', value: { id: 'content-1', name: 'initial', tracks: [], media: [] } }] })).rev, 1);
  const hostKey = key(), instance = key(); const states = [];
  const outgoing = startHostingHost({ service, roomId: p.projectId, hostKey, deviceId: 'host-original-device-0001', instance, record: () => c.credentialStore.peek(p.projectId), docBase: localBase, assetBase: `http://127.0.0.1:${c.assetPort}`, state: s => states.push(s), renewMs: 500 });
  t.after(() => outgoing.stop()); await waitFor(() => cloud.online(p.projectId), 10000, 'isolated tunnel');
  const discover = opts => discoverRoom({ service, roomId: p.projectId, username: 'member', deviceId: 'member-original-device-01', as: 'member', password: memberPassword, ...opts });
  await assert.rejects(discover({ password: key() }), e => e.status === 401);
  const route = await discover();
  const protocols = await buildAuthProtocols({ base: route.base, fetch: relayFetch(route.access), projectId: p.projectId, username: 'member', as: 'member', password: memberPassword, deviceId: 'member-original-device-01', deviceName: 'isolated-member' });
  const member = wsClient(route.base.replace('http:', 'ws:'), [...protocols, route.routeProtocol]); await member.opened; t.after(() => member.close());
  assert.equal((await ask(member, { type: 'project.open', projectId: p.projectId })).rev, 1);
  const edited = await ask(member, { type: 'project.op', projectId: p.projectId, opId: key(), ops: [{ op: 'set', path: '/name', value: 'member-edit' }] }); assert.equal(edited.rev, 2);
  assert.equal((await ask(host, { type: 'project.open', projectId: p.projectId })).project.name, 'member-edit');
  await ask(host, { type: 'project.op', projectId: p.projectId, opId: key(), ops: [{ op: 'set', path: '/name', value: 'host-edit' }] });
  assert.equal((await ask(member, { type: 'project.open', projectId: p.projectId })).project.name, 'host-edit');
  const issued = await ask(member, { type: 'auth.ticket', kind: 'asset', access: 'rw' }); assert.equal(issued.type, 'auth.ticket.ok');
  await authorizeRelayAsset(route, issued.ticket);
  const assets = createAssetClient({ base: route.asset, ticket: async () => issued.ticket });
  const bytes = randomBytes(50000), hash = createHash('sha256').update(bytes).digest('hex');
  assert.equal((await assets.put('media', bytes, { ext: 'bin' })).hash, hash); assert.deepEqual(Buffer.from(await assets.get('media', hash)), bytes);
  const denied = await fetch(`${route.asset}/media/${hash}`); assert.equal(denied.status, 401);
  const registry = fs.readFileSync(path.join(dir, 'directory.json'), 'utf8');
  assert.equal(registry.includes('host-edit'), false); assert.equal(registry.includes(creatorPassword), false); assert.equal(registry.includes(hostKey), false);
  await outgoing.stop({ deleted: true });
  await assert.rejects(discover(), e => e.status === 410);
});
